export const URL_EXCEPTIONS = ['/bio/',
  '/',
  '/login',
  '/registro',
  '/home',
  '/sobre',
  '/contato',
  '/planos',
  '/termos',
  '/privacidade',
  '/recuperar-senha',
  '/esqueci-senha',
  '/redefinir-senha',
  '/verify-email']